osf:
  server: minio
  timeToLive: 30000
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: test

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest